// BASE URL
export let REACT_APP_BASE_URL = process.env.REACT_APP_BASE_URL;

export let REACT_APP_TOKEN = process.env.REACT_APP_TOKEN;

// AB TESTING
export let REACT_APP_URL_EXPERIMENTS = process.env.REACT_APP_URL_EXPERIMENTS;
export let REACT_APP_URL_SESSION_COUNT = process.env.REACT_APP_URL_SESSION_COUNT;
export let REACT_APP_URL_VISITOR_COUNT = process.env.REACT_APP_URL_VISITOR_COUNT;
export let REACT_APP_URL_CONVERSION_RATE = process.env.REACT_APP_URL_CONVERSION_RATE;
export let REACT_APP_URL_CONVERSION_TABLE = process.env.REACT_APP_URL_CONVERSION_TABLE;
export let REACT_APP_EXPERIMENT_SUMMARY = process.env.REACT_APP_EXPERIMENT_SUMMARY;

// CONVERSIONS
export let REACT_APP_URL_SHOP_FUNNEL = process.env.REACT_APP_URL_SHOP_FUNNEL;
export let REACT_APP_URL_PRODUCT_CONVERSION = process.env.REACT_APP_URL_PRODUCT_CONVERSION;
export let REACT_APP_URL_LANDING_PAGE = process.env.REACT_APP_URL_LANDING_PAGE;
